# Generated by Django 5.2.16 on 2026-07-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('formulation', models.TextField()),
                ('category', models.CharField(choices=[('knowledge', 'Savoir'), ('hard_skill', 'Savoir-faire'), ('soft_skill', 'Savoir-etre')], max_length=24)),
                ('action_verb', models.CharField(blank=True, default='', max_length=80)),
                ('object', models.CharField(blank=True, default='', max_length=240)),
                ('context', models.TextField(blank=True, default='')),
                ('mastery_level', models.CharField(choices=[('beginner', 'Debutant'), ('junior', 'Junior'), ('confirmed', 'Confirme'), ('expert', 'Expert')], default='junior', max_length=24)),
                ('mastery_rationale', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('market_keywords', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(default='user', max_length=24)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'skill competencies',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deliverable', 'Deliverable'), ('metric', 'Metric'), ('feedback', 'Feedback'), ('certificate', 'Certificate'), ('portfolio_link', 'Portfolio link'), ('report', 'Report'), ('story', 'Story'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('metric', models.CharField(blank=True, default='', max_length=240)),
                ('trust_level', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('imported', 'Imported'), ('inferred_pending_review', 'Inferred pending review')], default='user_confirmed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SkillExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('professional', 'Professional'), ('project', 'Project'), ('education', 'Education'), ('volunteer', 'Volunteer'), ('personal', 'Personal'), ('travel', 'Travel'), ('cultural', 'Cultural'), ('other', 'Other')], default='professional', max_length=24)),
                ('organization', models.CharField(blank=True, default='', max_length=240)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('missions', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('people_context', models.TextField(blank=True, default='')),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillDevelopmentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.CharField(choices=[('beginner', 'Debutant'), ('junior', 'Junior'), ('confirmed', 'Confirme'), ('expert', 'Expert')], default='confirmed', max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('actions', models.JSONField(blank=True, default=list)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=24)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_actions', to='skills_portfolio.skillcompetency')),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='skillcompetency',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='competencies', to='skills_portfolio.skillevidence'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='source_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='skills_portfolio.skillexperience'),
        ),
        migrations.AddField(
            model_name='skillcompetency',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='competencies', to='skills_portfolio.skillexperience'),
        ),
        migrations.CreateModel(
            name='SkillExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=80)),
                ('model', models.CharField(blank=True, default='', max_length=160)),
                ('prompt_template', models.CharField(max_length=160)),
                ('input_hash', models.CharField(blank=True, default='', max_length=80)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_runs', to='skills_portfolio.skillexperience')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
