# Generated by Django 5.2.16 on 2026-07-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('education_type', models.CharField(choices=[('formation', 'Formation'), ('certification', 'Certification'), ('rncp', 'Titre RNCP'), ('professional', 'Formation professionnelle'), ('mooc', 'MOOC / e-learning')], default='formation', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planifiee'), ('in_progress', 'En cours'), ('completed', 'Terminee'), ('expired', 'Expiree')], default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('credential_id', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='skills_portfolio.skillexperience')),
            ],
            options={
                'ordering': ['-start_date', '-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EducationCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.CharField(choices=[('validated', 'Validee par cette formation'), ('acquired', 'Acquise pendant cette formation'), ('targeted', 'Objectif de cette formation')], default='acquired', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_links', to='skills_portfolio.skillcompetency')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_links', to='skills_portfolio.education')),
            ],
            options={
                'unique_together': {('education', 'competency')},
            },
        ),
        migrations.AddField(
            model_name='education',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='educations', through='skills_portfolio.EducationCompetency', to='skills_portfolio.skillcompetency'),
        ),
    ]
