# Generated by Django 5.2.16 on 2026-07-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ats', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('greenhouse_token', models.CharField(blank=True, max_length=200)),
                ('ashby_slug', models.CharField(blank=True, max_length=200)),
                ('lever_slug', models.CharField(blank=True, max_length=200)),
                ('careers_url', models.URLField(blank=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
