# Generated by Django 5.2.16 on 2026-07-15 10:23

from django.db import migrations, models


def import_portals_from_yaml(apps, schema_editor):
    """Seed DB from config/portals.yml after schema changes."""
    from pathlib import Path
    from django.conf import settings

    import yaml

    yaml_path = Path(settings.CAREER_OPS_ROOT) / "config" / "portals.yml"
    if not yaml_path.exists():
        return

    with open(yaml_path) as f:
        data = yaml.safe_load(f) or {}

    TitleFilter = apps.get_model("portals", "TitleFilter")
    Portal = apps.get_model("portals", "Portal")
    SearchQuery = apps.get_model("portals", "SearchQuery")
    JobBoard = apps.get_model("portals", "JobBoard")

    tf_data = data.get("title_filter", {})
    TitleFilter.objects.update_or_create(
        pk=1,
        defaults={
            "positive": tf_data.get("positive", []),
            "negative": tf_data.get("negative", []),
            "seniority_boost": tf_data.get("seniority_boost", []),
        },
    )

    for entry in data.get("tracked_companies", []):
        if not entry.get("name"):
            continue
        extra = {}
        KNOWN_PORTAL_FIELDS = {
            "name", "careers_url", "enabled", "api", "scan_method",
            "scan_query", "notes", "provider", "parser", "max_pages",
        }
        for k, v in entry.items():
            if k not in KNOWN_PORTAL_FIELDS:
                extra[k] = v

        Portal.objects.update_or_create(
            name=entry["name"],
            defaults={
                "careers_url": entry.get("careers_url", ""),
                "enabled": entry.get("enabled", True),
                "api_endpoint": entry.get("api", ""),
                "scan_method": entry.get("scan_method", "auto"),
                "scan_query": entry.get("scan_query", ""),
                "notes": entry.get("notes", ""),
                "provider": entry.get("provider", ""),
                "parser_config": entry.get("parser"),
                "max_pages": entry.get("max_pages"),
                "extra_config": extra,
            },
        )

    for entry in data.get("search_queries", []):
        query = entry.get("query", "")
        if not query:
            continue
        SearchQuery.objects.update_or_create(
            query=query,
            defaults={
                "name": entry.get("name", ""),
                "source": entry.get("source", ""),
                "enabled": entry.get("enabled", True),
            },
        )

    for entry in data.get("job_boards", []):
        if not entry.get("name"):
            continue
        extra = {}
        KNOWN_BOARD_FIELDS = {"name", "careers_url", "provider", "enabled", "notes"}
        for k, v in entry.items():
            if k not in KNOWN_BOARD_FIELDS:
                extra[k] = v

        JobBoard.objects.update_or_create(
            name=entry["name"],
            defaults={
                "careers_url": entry.get("careers_url", ""),
                "provider": entry.get("provider", ""),
                "enabled": entry.get("enabled", True),
                "notes": entry.get("notes", ""),
                "extra_config": extra,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('careers_url', models.URLField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TitleFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.JSONField(blank=True, default=list)),
                ('negative', models.JSONField(blank=True, default=list)),
                ('seniority_boost', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'title filter',
                'verbose_name_plural': 'title filters',
            },
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='portal',
            name='ashby_slug',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='greenhouse_token',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='lever_slug',
        ),
        migrations.AddField(
            model_name='portal',
            name='api_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portal',
            name='max_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='parser_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portal',
            name='scan_method',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('api', 'Direct API'), ('websearch', 'Web Search'), ('local_parser', 'Local Parser')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='portal',
            name='scan_query',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(import_portals_from_yaml, noop),
    ]
