# Generated by Django 5.2.16 on 2026-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_portals_enrich'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.JSONField(blank=True, default=list)),
                ('block', models.JSONField(blank=True, default=list)),
                ('always_allow', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'location filter',
                'verbose_name_plural': 'location filters',
            },
        ),
    ]
