from django.urls import path

from .views import (
    BenchmarkView,
    BenchmarkSummaryView,
    CompetenciesView,
    CompetencyDetailView,
    CompetencyReadinessView,
    CompetencyRejectView,
    CompetencyValidateView,
    CVBulletsView,
    DashboardView,
    DevelopmentPlanView,
    DiscoveryKeywordsView,
    DiscoveryProfileView,
    EducationAttachCompetencyView,
    EducationDetailView,
    EducationDetachCompetencyView,
    EducationsView,
    EvidenceAttachView,
    EvidenceDetailView,
    EvidenceDetachView,
    EvidenceView,
    ExportJsonView,
    ExportMarkdownView,
    ExportCvDataView,
    ExportCvMarkdownView,
    ExperienceDetailView,
    ExperiencesView,
    ExtractEducationView,
    ExtractExperienceView,
    ExtractFromExperienceView,
    ExtractPortalView,
    ExtractProfileView,
    FormalizeCompetencyView,
    InterviewQuestionsView,
    MasteryEvaluationView,
    ClarifyEvidenceView,
    ParseJDView,
    SkillGapsView,
    SuggestEvidenceView,
    ValidatedCompetenciesView,
)

urlpatterns = [
    # CRUD
    path("dashboard", DashboardView.as_view(), name="skills-dashboard"),
    path("experiences", ExperiencesView.as_view(), name="skills-experiences"),
    path("experiences/<int:pk>", ExperienceDetailView.as_view(), name="skills-experience-detail"),
    path("competencies", CompetenciesView.as_view(), name="skills-competencies"),
    path("competencies/<int:pk>", CompetencyDetailView.as_view(), name="skills-competency-detail"),
    path("competencies/<int:pk>/validate", CompetencyValidateView.as_view(), name="skills-competency-validate"),
    path("competencies/<int:pk>/reject", CompetencyRejectView.as_view(), name="skills-competency-reject"),
    path("competencies/<int:pk>/readiness", CompetencyReadinessView.as_view(), name="skills-competency-readiness"),
    path("evidence", EvidenceView.as_view(), name="skills-evidence"),
    path("evidence/<int:pk>", EvidenceDetailView.as_view(), name="skills-evidence-detail"),
    path("evidence/attach", EvidenceAttachView.as_view(), name="skills-evidence-attach"),
    path("evidence/detach", EvidenceDetachView.as_view(), name="skills-evidence-detach"),
    path("educations", EducationsView.as_view(), name="skills-educations"),
    path("educations/<int:pk>", EducationDetailView.as_view(), name="skills-education-detail"),
    path("educations/<int:pk>/attach-competency", EducationAttachCompetencyView.as_view(), name="skills-education-attach"),
    path("educations/<int:pk>/detach-competency", EducationDetachCompetencyView.as_view(), name="skills-education-detach"),
    # LLM-assisted
    path("llm/extract-from-experience", ExtractFromExperienceView.as_view(), name="skills-llm-extract"),
    path("llm/extract-experience", ExtractExperienceView.as_view(), name="skills-llm-extract-experience"),
    path("llm/extract-education", ExtractEducationView.as_view(), name="skills-llm-extract-education"),
    path("llm/extract-profile", ExtractProfileView.as_view(), name="skills-llm-extract-profile"),
    path("llm/extract-portal", ExtractPortalView.as_view(), name="skills-llm-extract-portal"),
    path("llm/formalize", FormalizeCompetencyView.as_view(), name="skills-llm-formalize"),
    path("llm/suggest-evidence", SuggestEvidenceView.as_view(), name="skills-llm-suggest-evidence"),
    path("llm/evaluate-mastery", MasteryEvaluationView.as_view(), name="skills-llm-evaluate-mastery"),
    path("llm/clarify-evidence", ClarifyEvidenceView.as_view(), name="skills-llm-clarify-evidence"),
    path("llm/benchmark", BenchmarkView.as_view(), name="skills-llm-benchmark"),
    path("llm/benchmark-summary", BenchmarkSummaryView.as_view(), name="skills-llm-benchmark-summary"),
    path("llm/parse-jd", ParseJDView.as_view(), name="skills-llm-parse-jd"),
    path("llm/development-plan", DevelopmentPlanView.as_view(), name="skills-llm-dev-plan"),
    # Export
    path("export/json", ExportJsonView.as_view(), name="skills-export-json"),
    path("export/markdown", ExportMarkdownView.as_view(), name="skills-export-markdown"),
    path("export/cvdata", ExportCvDataView.as_view(), name="skills-export-cvdata"),
    path("export/cv-markdown", ExportCvMarkdownView.as_view(), name="skills-export-cv-markdown"),
    # Integration — deterministic (no LLM)
    path("integration/validated", ValidatedCompetenciesView.as_view(), name="skills-integration-validated"),
    path("integration/skill-gaps", SkillGapsView.as_view(), name="skills-integration-skill-gaps"),
    path("integration/discovery-keywords", DiscoveryKeywordsView.as_view(), name="skills-integration-discovery-keywords"),
    # Integration — LLM-assisted
    path("llm/suggest-cv-bullets", CVBulletsView.as_view(), name="skills-llm-cv-bullets"),
    path("llm/suggest-interview-questions", InterviewQuestionsView.as_view(), name="skills-llm-interview-questions"),
    path("llm/discovery-profile", DiscoveryProfileView.as_view(), name="skills-llm-discovery-profile"),
]

