# Generated by Django 5.2.16 on 2026-07-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=300)),
                ('via', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(default='Evaluated', max_length=40)),
                ('score', models.CharField(blank=True, default='', max_length=20)),
                ('has_pdf', models.BooleanField(default=False)),
                ('report_file', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('synced_to_file', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('compensation', models.CharField(blank=True, max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('synced_to_file', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['done', '-posted_at', 'company'],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-first_seen'],
                'unique_together': {('url', 'source')},
            },
        ),
    ]
